### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Tommy Toukan",
    "company": "kblDesigners",
    "address": "St. Louis, Mo, USA",
    "phone": "9576476464",
    "email": "tommyt@kbldesigners.com",
    "password": "Yoshi1988"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "tommyt@kbldesigners.com",
    "password": "Yoshi1988"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjQ4OTMyODc5LCJleHAiOjE2NDg5MzM3Nzl9.NoK0whkn7pcrOv-Bn1MO7oSvCrdhqOmZw5b-AZ7O1B8


### Tokens routers

## Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjQ4OTMyODc5LCJleHAiOjE2NTE1MjQ4Nzl9.G5jvamR9iyb0VQMEEFiYYTbiVZrjFHi_IOgzHeDTrWY


### Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "tommyt@kbldesigners.com"

}

