### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Tommy Toukan",
    "company": "kblDesigners",
    "address": "St. Louis, Mo, USA",
    "phone": "9576476464",
    "email": "tommyt@kbldesigners.com",
    "password": "Yoshi1988"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "tommyt@kbldesigners.com",
    "password": "Yoshi1988"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjQ4OTE5OTI0LCJleHAiOjE2NDg5MjA4MjR9.L6tEWmK8iPj9LOzx021gZC2RwO4mz2oPR-YBn3R8Jfw


### Tokens routers

## Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjQ4OTE5OTI0LCJleHAiOjE2NTE1MTE5MjR9.VTdSs3AyDVGLUecLlJ3gkkoFgCjAxHpWMYpztC3nqXY


### Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "tommyt@kbldesigners.com"

}